# Generated by Django 3.1.7 on 2021-03-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, max_length=255, null=True, verbose_name='Задания')),
                ('create_date', models.DateField(verbose_name='Дата Добавления')),
                ('dueon_date', models.DateField(verbose_name='Дедлайн')),
                ('owner', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('mark', models.BooleanField(verbose_name='оценка')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Список Задании',
            },
        ),
    ]
