# Generated by Django 3.1.7 on 2021-03-20 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['create_date'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Список Задании'},
        ),
    ]
